### ISSUE TITLE
Port Seaside to 3.6.0

### ISSUE THREAD

**Issue by dalehenrich** [SeasideSt/Seaside#1226]
- [x] #1222 - "Drop Swazoo from Seaside for GemStone?"
- [x] #1223 - "The class GsContext is in both Seaside (Seaside-GemStone-Core) and Grease (Grease-GemStone-Core)"
- [x] with PR glassdb/glass#38, GLASS and tODE tests are passing for 3.6.0
- [x] SeasideSt/Parasol#41
- [x] GsDevKit/zinc#92
- [x] SeasideSt/Parasol#43
- [x] SeasideSt/Grease#111
- [x] Metacello/metacello#531
- [x] all tests passing

**Comment by dalehenrich** [comment]
initial test results (`test image`). Wasn't running ChromeDriver for the WAWebDriverFunctionalTestCases, so they are unknown at the moment:
```
3936 run, 3902 passes, 9 expected defects, 3 failures, 22 errors, 0 unexpected passes
	3936 tests
	3936 run
	3902 passes
	9 expected defects
	3 failures
WAConfigurationHandlerTest debug: #testSwaggerSpecificationFile
WAMimeTypeHandlerTest debug: #testSwaggerSpecificationFile
WAResponseGeneratorTest debug: #testInternalError
	22 errors
WAWebDriverFunctionalTestCase debug: #testBatchFunctionalTest
WAWebDriverFunctionalTestCase debug: #testButtonFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCallbackFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCallbackSecurityFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCanvasTableFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCanvasTagFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCookieFunctionalTest
WAWebDriverFunctionalTestCase debug: #testDateSelectorFunctionalTest
WAWebDriverFunctionalTestCase debug: #testDateTimeFunctionalTest
WAWebDriverFunctionalTestCase debug: #testDelayFunctionalTest
WAWebDriverFunctionalTestCase debug: #testDelegationFunctionalTest
WAWebDriverFunctionalTestCase debug: #testEncodingFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowClosureFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowClosureFunctionalTest2
WAWebDriverFunctionalTestCase debug: #testFlowConvenienceFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowDelegationFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowRenderingCallFunctionalTest
WAWebDriverFunctionalTestCase debug: #testHomeFunctionalTest
WAWebDriverFunctionalTestCase debug: #testWAHtml5ContentTest
WAWebDriverFunctionalTestCase debug: #testWAHtml5ElementsTest
WAWebDriverFunctionalTestCase debug: #testWAHtml5InputTest
	0 unexpected passes
```

**Comment by dalehenrich** [comment]
3.5.4 test results (`test image` no ChromeDriver):
```
4079 run, 4038 passes, 9 expected defects, 10 failures, 22 errors, 0 unexpected passes
	4079 tests
	4079 run
	4038 passes
	9 expected defects
	10 failures
FastCGISeasideGemServerTests debug: #testStartRestartStopServer
SwazooSeasideGemServerTests debug: #testWAGemStoneWalkbackErrorHandler
WAConfigurationHandlerTest debug: #testSwaggerSpecificationFile
WAMimeTypeHandlerTest debug: #testSwaggerSpecificationFile
ZnSeasideGemServerTests debug: #testStartRestartStopServer
ZnSeasideGemServerTests debug: #testWAGemStoneWalkbackErrorHandler
ZnSeasideGemServerTests debug: #testWAGemStoneWalkbackErrorHandlerInteractive
ZnSeasideNewGemServerTests debug: #testStartRestartStopServer
ZnSeasideNewGemServerTests debug: #testWAGemStoneWalkbackErrorHandler
ZnSeasideNewGemServerTests debug: #testWAGemStoneWalkbackErrorHandlerInteractive
	22 errors
WAWebDriverFunctionalTestCase debug: #testBatchFunctionalTest
WAWebDriverFunctionalTestCase debug: #testButtonFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCallbackFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCallbackSecurityFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCanvasTableFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCanvasTagFunctionalTest
WAWebDriverFunctionalTestCase debug: #testCookieFunctionalTest
WAWebDriverFunctionalTestCase debug: #testDateSelectorFunctionalTest
WAWebDriverFunctionalTestCase debug: #testDateTimeFunctionalTest
WAWebDriverFunctionalTestCase debug: #testDelayFunctionalTest
WAWebDriverFunctionalTestCase debug: #testDelegationFunctionalTest
WAWebDriverFunctionalTestCase debug: #testEncodingFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowClosureFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowClosureFunctionalTest2
WAWebDriverFunctionalTestCase debug: #testFlowConvenienceFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowDelegationFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowRenderingCallFunctionalTest
WAWebDriverFunctionalTestCase debug: #testHomeFunctionalTest
WAWebDriverFunctionalTestCase debug: #testWAHtml5ContentTest
WAWebDriverFunctionalTestCase debug: #testWAHtml5ElementsTest
WAWebDriverFunctionalTestCase debug: #testWAHtml5InputTest
	0 unexpected passes
```

**Comment by dalehenrich** [comment]
Update on 3.6.0 with ChromeDriver running (Parasol tests all passing):
```
3936 run, 3924 passes, 9 expected defects, 3 failures, 0 errors, 0 unexpected passes
	3936 tests
	3936 run
	3924 passes
	9 expected defects
	3 failures
WAConfigurationHandlerTest debug: #testSwaggerSpecificationFile
WAMimeTypeHandlerTest debug: #testSwaggerSpecificationFile
WAResponseGeneratorTest debug: #testInternalError
	0 errors
	0 unexpected passes
```

**Comment by dalehenrich** [comment]
hmmm, I saw that there are 9 expected defects:
```
3936 run, 3924 passes, 9 expected defects, 3 failures, 0 errors, 0 unexpected passes
  3936 tests
MCTraitDefinitionTest debug: #testCannotLoadClass
OverriddenBaseMethodsTest debug: #testOverriddenBaseMethods
TDShellFsToFsRsyncCommandTests debug: #testRsyncFileSystemLeaf
WAWebDriverFunctionalTestCase debug: #testContextFunctionalTest
WAWebDriverFunctionalTestCase debug: #testExceptionFunctionalTest
WAWebDriverFunctionalTestCase debug: #testExpiryFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFilterFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowErrorFunctionalTest
ZnHTTPSTests debug: #testRequestResponse
```
... these three tests make sense for being expected defects:
```
MCTraitDefinitionTest debug: #testCannotLoadClass
OverriddenBaseMethodsTest debug: #testOverriddenBaseMethods
TDShellFsToFsRsyncCommandTests debug: #testRsyncFileSystemLeaf
```
but I'm curious about the others:
```
WAWebDriverFunctionalTestCase debug: #testContextFunctionalTest
WAWebDriverFunctionalTestCase debug: #testExceptionFunctionalTest
WAWebDriverFunctionalTestCase debug: #testExpiryFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFilterFunctionalTest
WAWebDriverFunctionalTestCase debug: #testFlowErrorFunctionalTest
ZnHTTPSTests debug: #testRequestResponse
```
@jbrichau, do you have an opinion about the validity of these expected defects? Looks like `ZnHTTPSTests debug: testRequestResponse` is atually changed in the most recent pharo versions, so I will make that change ... so I'm mainly curious about the WAWebDriverFunctionalTestCase expected failures ... Presumably they are valid ... but these is a bug in GemStone, we might be able to fix the bug in 3.6.0 if neeeded ...

**Comment by jbrichau** [comment]
@dalehenrich You can ignore these expected failures. They are empty tests. I keep them in the code base to keep track of which tests I still need to add. It's more a strategy to keep track of the conversion of the manual tests to the automated tests.
